package com.statedriven.agent;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.http.*;import org.springframework.http.codec.ServerSentEvent;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import reactor.core.publisher.*;
@RestController final class AgentController {
 private final ObjectMapper json;private final ConfigRepository configs;private final SessionRepository sessions;private final AgentEngine engine;private final Map<String,Object> locks=new ConcurrentHashMap<>();AgentController(ObjectMapper j,ConfigRepository c,SessionRepository s,AgentEngine e){json=j;configs=c;sessions=s;engine=e;}
 @GetMapping("/health") Map<String,Object> health(){return Map.of("status","ok","config_root",configs.root().toString(),"available_configs",configs.list().size());}
 @GetMapping("/configs") List<?> configs(){return configs.list().stream().map(x->Map.of("config_ref",x.ref(),"sha256",x.sha256(),"agent_name",x.config().path("name").asText(),"tools",x.config().path("tools"),"workflow_phases",x.config().at("/workflow/phases"))).toList();}
 @PostMapping("/sessions") Mono<ResponseEntity<?>> create(@RequestBody ObjectNode q){try{String goal=q.path("user_prompt").asText();if(goal.isBlank())return Mono.just(ResponseEntity.unprocessableEntity().build());var c=configs.resolve(q.path("config_ref").asText("test-case-1.yaml"));ObjectNode s=json.createObjectNode();s.put("id",UUID.randomUUID().toString());s.put("goal",goal);s.put("config_ref",c.ref());s.put("config_sha256",c.sha256());s.put("status","active");s.put("step_count",0);s.put("run_count",0);s.withArray("memory").addObject().put("role","user").put("content",goal);s.putArray("compaction_events");if(c.config().has("workflow")){ObjectNode w=s.putObject("workflow");w.put("active_phase",c.config().at("/workflow/entry_phase").asText());w.putArray("completed_phases");w.putArray("observed_evidence");w.putArray("transitions");}ObjectNode out=json.createObjectNode();out.set("session",s);out.put("message","Session created with immutable config "+c.ref()+"@"+c.sha256().substring(0,12)+".");return sessions.save(s,c.config(),event("session_created")).thenReturn(ResponseEntity.status(201).body(out));}catch(Exception e){return Mono.just(ResponseEntity.unprocessableEntity().build());}}
 @GetMapping("/sessions/{session_id}") Mono<ResponseEntity<ObjectNode>> get(@PathVariable("session_id") String sessionId){return sessions.get(sessionId).map(x->ResponseEntity.ok(x.state())).defaultIfEmpty(ResponseEntity.notFound().build());}
 @PostMapping("/sessions/{session_id}/messages") Mono<ResponseEntity<?>> message(@PathVariable("session_id") String sessionId,@RequestBody ObjectNode q){return sessions.get(sessionId).flatMap(x->{if(!"active".equals(x.state().path("status").asText()))return Mono.just(ResponseEntity.status(409).build());String content=q.path("content").asText();if(content.isBlank())return Mono.just(ResponseEntity.unprocessableEntity().build());x.state().withArray("memory").addObject().put("role","user").put("content",content);ObjectNode o=json.createObjectNode();o.set("session",x.state());o.put("message","User input appended to session memory.");return sessions.save(x.state(),x.config(),event("user_message_appended")).thenReturn(ResponseEntity.ok(o));}).defaultIfEmpty(ResponseEntity.notFound().build());}
 @PostMapping("/sessions/{session_id}/run") Mono<ResponseEntity<ObjectNode>> run(@PathVariable("session_id") String sessionId,@RequestBody ObjectNode q){
  return sessions.get(sessionId).flatMap(persisted -> {
   if(!"active".equals(persisted.state().path("status").asText())) return Mono.just(ResponseEntity.ok(response(persisted.state(),"Session is terminal; use POST /sessions/{session_id}/resume to continue it.")));
   return engine.run(persisted.state(),persisted.config(),steps(q,persisted.config()),e->sessions.save(persisted.state(),persisted.config(),e))
    .flatMap(done -> sessions.save(done,persisted.config(),event("run_finished")).thenReturn(ResponseEntity.ok(response(done,done.path("final_answer").asText("Run stopped.")))));
  }).defaultIfEmpty(ResponseEntity.notFound().build());
 }
 @PostMapping(value="/sessions/{session_id}/run/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) Flux<ServerSentEvent<ObjectNode>> stream(@PathVariable("session_id") String sessionId,@RequestBody ObjectNode q){return lifecycle(sessionId,q,false);}
 @PostMapping(value="/sessions/{session_id}/resume",produces=MediaType.TEXT_EVENT_STREAM_VALUE) Flux<ServerSentEvent<ObjectNode>> resume(@PathVariable("session_id") String sessionId,@RequestBody ObjectNode q){return lifecycle(sessionId,q,true);}
 private Flux<ServerSentEvent<ObjectNode>> lifecycle(String sessionId,ObjectNode q,boolean resume){
  return sessions.get(sessionId).flatMapMany(persisted -> {
   ObjectNode s=persisted.state();
   if(resume){s.put("status","active");s.remove("final_answer");if(!q.path("content").asText().isBlank())s.withArray("memory").addObject().put("role","user").put("content",q.path("content").asText());}
   if(!resume&&!"active".equals(s.path("status").asText())) return Flux.error(new ResponseStatusException(HttpStatus.CONFLICT,"Session is terminal; use POST /sessions/{session_id}/resume to continue it"));
   List<ObjectNode> events=new ArrayList<>(); ObjectNode setup=event("status","message",resume?"Restored immutable config, workflow evidence, memory, and compaction ledger.":"Agent initialized from persisted session state.");
   Mono<Void> before=resume?sessions.save(s,persisted.config(),event("session_resumed","has_new_user_message",!q.path("content").asText().isBlank())):Mono.empty();
   if(resume)events.add(event("status","message","Session restored from PostgreSQL; resuming agent work."));
   if(persisted.config().at("/output/verbose_setup").asBoolean(false))before=before.then(sessions.save(s,persisted.config(),setup).doOnSuccess(v->events.add(setup)));
   return before
    .then(engine.run(s,persisted.config(),steps(q,persisted.config()),e->sessions.save(s,persisted.config(),e).doOnSuccess(v->events.add(e))))
    .flatMap(done->{ObjectNode finish=event("run_finished","status",done.path("status").asText());events.add(finish);events.add(event("status","message","Agent run finished.","status",done.path("status").asText()));return sessions.save(done,persisted.config(),finish).thenReturn(events);})
    .flatMapMany(Flux::fromIterable);
  }).map(e->ServerSentEvent.builder(e).build());
 }
 private <T> Mono<T> within(String id,java.util.function.Supplier<Mono<T>> work){Object lock=locks.computeIfAbsent(id,k->new Object());return Mono.defer(()->{synchronized(lock){return work.get();}});}
 private int steps(ObjectNode q,ObjectNode c){if(q.has("max_steps")){int n=q.path("max_steps").asInt();if(n<1||n>50)throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,"max_steps must be between 1 and 50");return n;}return c.at("/memory/max_steps").asInt();}private ObjectNode response(ObjectNode s,String m){ObjectNode o=json.createObjectNode();o.set("session",s);o.put("message",m);return o;}private ObjectNode event(String type,Object...kv){ObjectNode e=json.createObjectNode();e.put("type",type);for(int i=0;i<kv.length;i+=2)e.set(kv[i].toString(),json.valueToTree(kv[i+1]));return e;}
}
