package com.statedriven.agent;

import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import java.util.*; import java.util.regex.*; import org.springframework.r2dbc.core.DatabaseClient; import org.springframework.stereotype.Component; import reactor.core.publisher.Mono;
@Component final class FixtureTools {
 private final DatabaseClient db;private final ObjectMapper json;private static final Pattern IP=Pattern.compile("^(?<ip>(?:\\d{1,3}\\.){3}\\d{1,3})\\s+.*?\\s(?<status>\\d{3})$"); FixtureTools(DatabaseClient db,ObjectMapper json){this.db=db;this.json=json;}
 Mono<String> execute(String n,JsonNode a){try{return switch(n){case "inspect_log"->logs().map(x->{int start=a.path("start_line").asInt(),count=a.path("line_count").asInt();StringBuilder b=new StringBuilder();for(int i=Math.max(0,start-1);i<Math.min(x.size(),start-1+count);i++)b.append(i+1).append(": ").append(x.get(i)).append("\n");return b.toString().strip();});case "analyze_500_ips"->analyze(a.path("robust_parser").asBoolean());case "validate_top_offending_ip"->expectedIp().map(x->obj(Map.of("valid",a.path("ip").asText().equals(x[0])&&a.path("count").asInt()==Integer.parseInt(x[1]),"message",a.path("ip").asText().equals(x[0])&&a.path("count").asInt()==Integer.parseInt(x[1])?"Validated.":"Incorrect; inspect parsing and retry.")));case "inspect_sql_schema"->schema();case "query_chicago_q1_revenue"->revenue(a.path("normalize_keys").asBoolean(),a.path("normalize_city").asBoolean());case "validate_chicago_q1_revenue"->revenue(true,true).map(x->{try{return obj(Map.of("valid",Math.round(a.path("total").asDouble()*100)==Math.round(json.readTree(x).path("total").asDouble()*100),"expected_hint","Normalize city case and ID_ foreign keys."));}catch(Exception e){return "ERROR: "+e;}});case "inspect_employee_audit_schema"->employees().map(rows->obj(Map.of("schema",Map.of("table","employees","columns",List.of("emp_id INTEGER","name TEXT","age TEXT","salary TEXT","city TEXT")),"record_count",rows.size(),"rules","age is invalid when NULL or semicolon-delimited; salary is invalid when currency-formatted or UNKNOWN; city matching is case-insensitive.")));case "audit_employee_phase_1"->audit(a.path("parser").asText());case "calculate_new_york_median_salary"->median(a.path("normalize_city").asBoolean(),a.path("exclude_invalid_salary").asBoolean());case "generate_employee_phase_3_report"->report(a.path("normalize_city").asBoolean(),a.path("drop_invalid_age").asBoolean());case "validate_employee_audit"->Mono.just(obj(Map.of("valid",a.path("phase_1_logged").asBoolean()&&a.path("normalize_city").asBoolean()&&a.path("drop_invalid_age").asBoolean()&&Math.round(a.path("median_salary").asDouble()*100)==9250000,"expected_median_salary",92500.0,"hint","Validated all three phases.")));default->Mono.just("ERROR: unknown tool '"+n+"'.");};}catch(Exception e){return Mono.just("ERROR: "+e.getClass().getSimpleName()+": "+e.getMessage());}}
 private Mono<List<String>> logs(){return db.sql("SELECT line FROM agent_fixture_access_logs ORDER BY line_number").map((r,m)->r.get(0,String.class)).all().collectList();}
 private Mono<String> analyze(boolean robust){return logs().map(lines->{Map<String,Integer> c=new HashMap<>();for(int i=0;i<lines.size();i++){String l=lines.get(i);Matcher m=IP.matcher(l);if(!robust){String[] f=l.split(" ");if(f.length<=7)return "ERROR: naive parser failed at line "+(i+1)+": IndexOutOfBoundsException. Try robust_parser=true.";if("500".equals(f[7]))c.merge(f[0],1,Integer::sum);}else if(m.matches()&&"500".equals(m.group("status")))c.merge(m.group("ip"),1,Integer::sum);}List<?> top=c.entrySet().stream().sorted((x,y)->Integer.compare(y.getValue(),x.getValue())).limit(5).map(x->List.of(x.getKey(),x.getValue())).toList();return obj(Map.of("top",top,"malformed_records_ignored",robust?10:0));});}
 private Mono<String[]> expectedIp(){return analyze(true).map(x->{try{JsonNode t=json.readTree(x).at("/top/0");return new String[]{t.get(0).asText(),t.get(1).asText()};}catch(Exception e){throw new IllegalStateException(e);}});}
 private Mono<String> schema(){return Mono.just(obj(Map.of("schema",Map.of("customers",List.of(),"orders",List.of()),"chicago_examples",List.of(),"string_key_examples",List.of())));}
 private Mono<String> revenue(boolean keys,boolean city){String key=keys?"CAST(REPLACE(o.cust_id, 'ID_', '') AS INTEGER)":"o.cust_id::INTEGER", condition=city?"lower(c.city) = 'chicago'":"c.city = 'Chicago'";return db.sql("SELECT ROUND(COALESCE(SUM(o.amount),0),2) total FROM agent_fixture_orders o JOIN agent_fixture_customers c ON c.id="+key+" WHERE "+condition+" AND o.ordered_at >= '2026-01-01' AND o.ordered_at < '2026-04-01'").map((r,m)->r.get("total",Number.class)).one().map(x->obj(Map.of("total",x.doubleValue(),"normalize_keys",keys,"normalize_city",city)));}
 private Mono<List<List<String>>> employees(){return db.sql("SELECT emp_id,name,age,salary,city FROM agent_fixture_employees ORDER BY emp_id").map((r,m)->List.of(r.get(0).toString(),r.get(1,String.class),r.get(2,String.class),r.get(3,String.class),r.get(4,String.class))).all().collectList();}
 private Mono<String> audit(String p){
  if("naive".equals(p)) return Mono.just(parserFailure(10,"salary","$80,000"));
  if("currency_cleaned".equals(p)) return Mono.just(parserFailure(15,"age","NULL"));
  if("null_cleaned".equals(p)) return Mono.just(parserFailure(22,"age","41; extra_field_corrupted"));
  if(!"robust".equals(p)) return Mono.just("ERROR: parser must be naive, currency_cleaned, null_cleaned, or robust.");
  return employees().map(rows->{ List<String> age=new ArrayList<>(), salary=new ArrayList<>();
   for(List<String> r:rows){if("NULL".equals(r.get(2))||r.get(2).contains(";"))age.add(r.get(0));if("UNKNOWN".equals(r.get(3))||r.get(3).startsWith("$"))salary.add(r.get(0));}
   Set<String> both=new TreeSet<>(); both.addAll(age); both.addAll(salary);
   return obj(Map.of("phase","Phase 1","corrupted_age_ids",age,"corrupted_salary_ids",salary,"corrupted_row_ids",both,"status","logged"));
  });
 }
 private String parserFailure(int row,String field,String value){StringBuilder b=new StringBuilder("ERROR: Phase 1 parser crashed at employee ").append(row).append("; ").append(field).append("='").append(value).append("'.\nTraceback (most recent call last):\nValueError: unsupported ").append(field).append(" representation '").append(value).append("'\nParser window (not a successful audit):\n");for(int i=Math.max(1,row-8);i<row+48;i++)b.append(String.format("  %4d | parsed_%s[%d] = %s_parser(record[%d])%n",i,field,i,field,i));b.append("Revise only the parser assumption exposed by this failure, then retry incrementally.");return b.toString();}
 private Mono<String> median(boolean city,boolean valid){if(!valid)return Mono.just("AssertionError: salary array contains UNKNOWN; filter invalid salary fields before median().");if(!city)return Mono.just("AssertionError: Expected median 92500, but your script calculated 71000. Match city case-insensitively.");return employees().map(rows->{List<Double> n=new ArrayList<>();for(var r:rows)if("new york".equalsIgnoreCase(r.get(4))&&!"UNKNOWN".equals(r.get(3))&&!r.get(3).startsWith("$"))n.add(Double.valueOf(r.get(3)));Collections.sort(n);double m=n.size()%2==0?(n.get(n.size()/2-1)+n.get(n.size()/2))/2:n.get(n.size()/2);return obj(Map.of("phase","Phase 2","median_salary",m,"valid_new_york_employees",n.size(),"status","calculated"));});}
 private Mono<String> report(boolean city,boolean age){if(!city)return Mono.just("ERROR: Phase 3 would split New York and new york. Set normalize_city=true.");if(!age)return Mono.just("ERROR: Phase 3 cannot average age while NULL and semicolon-corrupted ages remain. Set drop_invalid_age=true.");return employees().map(rows->{Map<String,List<Integer>> groups=new TreeMap<>();for(var r:rows)if(!"NULL".equals(r.get(2))&&!r.get(2).contains(";")){String k=Arrays.stream(r.get(4).toLowerCase().split(" ")).map(x->x.substring(0,1).toUpperCase()+x.substring(1)).reduce((x,y)->x+" "+y).orElse("");groups.computeIfAbsent(k,x->new ArrayList<>()).add(Integer.valueOf(r.get(2)));}StringBuilder s=new StringBuilder("Phase 3 — clean city audit\n| City | Valid headcount | Average age |\n| --- | ---: | ---: |\n");groups.forEach((k,v)->s.append("| ").append(k).append(" | ").append(v.size()).append(" | ").append(String.format(Locale.ROOT,"%.2f",v.stream().mapToInt(x->x).average().orElse(0))).append(" |\n"));s.append("\nPhase 3 normalization trace (diagnostic evidence):\n");for(int i=1;i<=48;i++)s.append(String.format("normalization-check %02d: city=lowercase, age=NULL-or-semicolon excluded, salary=UNKNOWN-or-currency excluded, aggregate=verified%n",i));return s.toString();});}
 private String obj(Object x){try{return json.writeValueAsString(x);}catch(Exception e){throw new IllegalStateException(e);}}
}
