package com.statedriven.agent;

import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import java.time.Duration; import java.util.*; import org.springframework.stereotype.Component; import org.springframework.core.env.Environment; import org.springframework.web.reactive.function.client.WebClient; import reactor.core.publisher.Mono;
@Component final class ModelClient {
 private final ObjectMapper json; private final Environment environment; private final WebClient http=WebClient.builder().build(); ModelClient(ObjectMapper json,Environment environment){this.json=json;this.environment=environment;}
 Mono<ObjectNode> decide(ObjectNode config,ArrayNode messages){ObjectNode body=json.createObjectNode();body.put("model",config.path("model").asText());body.set("messages",messages);ArrayNode tools=body.putArray("tools");for(JsonNode tool:config.path("tools")){ObjectNode x=tools.addObject();x.put("type","function");x.set("function",tool);}body.put("tool_choice","auto");body.put("temperature",config.at("/llm/temperature").asDouble(.1));return post(config,body).map(reply->{JsonNode choice=reply.at("/choices/0/message");ObjectNode d=json.createObjectNode();JsonNode call=choice.at("/tool_calls/0");if(!call.isMissingNode()){try{d.put("type","tool");d.put("id",call.path("id").asText("call_1"));d.put("name",call.at("/function/name").asText());d.set("arguments",json.readTree(call.at("/function/arguments").asText("{}")));}catch(Exception e){d.put("type","final");d.put("content","LLM emitted invalid tool arguments: "+e.getMessage());}}else{d.put("type","final");d.put("content",choice.path("content").asText("No final answer was returned."));}return d;});}
 Mono<String> compact(ObjectNode c,String goal,ArrayNode history,String existing,boolean hybrid){String prompt=hybrid?"You are the hybrid compaction and reflection engine for an autonomous agent. Analyze the historical prefix only. The primary agent separately preserves its recent raw working buffer, so do not reproduce, summarize, truncate, or invent raw messages here. Extract durable environmental constraints and lessons as imperative operational rules. Keep dead ends precise and short. Preserve only verified facts; mark uncertainty instead of promoting guesses to rules. Return exactly this structure and no surrounding prose: <COMPACTED_STATE><USER_GOAL>Restate the original goal without changing its parameters or definitions.</USER_GOAL><GLOBAL_LESSON_LEDGER>- Imperative rules for permanent constraints or discoveries; none if no verified lessons.</GLOBAL_LESSON_LEDGER><DEAD_ENDS>- One-sentence failed approaches and why they failed; none if no verified dead ends.</DEAD_ENDS><CURRENT_LOCAL_PIVOT>State the most important active hypothesis or next operational focus in one sentence.</CURRENT_LOCAL_PIVOT></COMPACTED_STATE> The raw working buffer is retained by the primary agent outside this response.":"Create a compacted context state for an agent. Preserve only verified facts. Use exactly these headings: - Core Objective - Universal Truths Discovered - Dead Ends - Current Local Pivot. Do not invent facts. The original goal is protected separately. Do not include raw history.";ObjectNode b=json.createObjectNode();b.put("model",c.path("model").asText());b.put("temperature",0);ArrayNode m=b.putArray("messages");m.addObject().put("role","system").put("content",prompt);m.addObject().put("role","user").put("content","Goal: "+goal+"\nPrevious ledger: "+(existing==null?"none":existing)+"\nHistorical prefix:\n"+history);return post(c,b).map(x->x.at("/choices/0/message/content").asText()).filter(s->!s.isBlank()).onErrorReturn(fallback(goal,hybrid));}
 private Mono<JsonNode> post(ObjectNode c,ObjectNode body){String base=c.at("/llm/base_url").asText().replaceAll("/+$","");String url=base.endsWith("/chat/completions")?base:base+"/chat/completions";String key=environment.getProperty(c.at("/llm/api_key_env").asText("OPENAI_API_KEY"),"local-not-required");return http.post().uri(url).header("Authorization","Bearer "+key).bodyValue(body).retrieve().bodyToMono(JsonNode.class).timeout(Duration.ofSeconds(c.at("/llm/timeout_seconds").asLong(90)));}
 private static String fallback(String goal,boolean hybrid){if(!hybrid)return "- Core Objective: "+goal+"\n- Universal Truths Discovered: none verified\n- Dead Ends: none verified\n- Current Local Pivot: Review retained raw turns.";return "<COMPACTED_STATE>\n<USER_GOAL>\n"+goal+"\n</USER_GOAL>\n<GLOBAL_LESSON_LEDGER>\n- No verified global lessons extracted.\n</GLOBAL_LESSON_LEDGER>\n<DEAD_ENDS>\n- No verified dead ends extracted; inspect the retained raw working buffer.\n</DEAD_ENDS>\n<CURRENT_LOCAL_PIVOT>\nReview the retained raw working buffer and continue from the latest verified state.\n</CURRENT_LOCAL_PIVOT>\n</COMPACTED_STATE>";}
}
