package com.statedriven.agent;

import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.ObjectNode; import java.util.UUID; import org.springframework.r2dbc.core.DatabaseClient; import org.springframework.stereotype.Repository; import reactor.core.publisher.Mono;
@Repository class SessionRepository {
 record Persisted(ObjectNode state,ObjectNode config){} private final DatabaseClient db;private final ObjectMapper json; SessionRepository(DatabaseClient db,ObjectMapper json){this.db=db;this.json=json;}
 Mono<Void> initialize(){return db.sql("CREATE TABLE IF NOT EXISTS agent_sessions (session_id UUID PRIMARY KEY,state JSONB NOT NULL,config JSONB NOT NULL,config_ref TEXT,config_sha256 TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())").then().then(db.sql("CREATE TABLE IF NOT EXISTS agent_session_events (event_id BIGSERIAL PRIMARY KEY,session_id UUID NOT NULL REFERENCES agent_sessions(session_id) ON DELETE CASCADE,event JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now())").then()).then(db.sql("CREATE INDEX IF NOT EXISTS agent_session_events_session_id_idx ON agent_session_events(session_id,event_id)").then());}
 Mono<Void> save(ObjectNode s,ObjectNode c,JsonNode e){return db.sql("INSERT INTO agent_sessions(session_id,state,config,config_ref,config_sha256) VALUES(:id,CAST(:s AS jsonb),CAST(:c AS jsonb),:r,:h) ON CONFLICT(session_id) DO UPDATE SET state=EXCLUDED.state,config=EXCLUDED.config,config_ref=EXCLUDED.config_ref,config_sha256=EXCLUDED.config_sha256,updated_at=now()").bind("id",UUID.fromString(s.path("id").asText())).bind("s",s.toString()).bind("c",c.toString()).bind("r",s.path("config_ref").asText()).bind("h",s.path("config_sha256").asText()).then().then(e==null?Mono.empty():db.sql("INSERT INTO agent_session_events(session_id,event) VALUES(:id,CAST(:e AS jsonb))").bind("id",UUID.fromString(s.path("id").asText())).bind("e",e.toString()).then());}
 Mono<Persisted> get(String id){try{return db.sql("SELECT state::text,config::text FROM agent_sessions WHERE session_id=:id").bind("id",UUID.fromString(id)).map((r,m)->new String[]{r.get(0,String.class),r.get(1,String.class)}).one().map(x->{try{return new Persisted((ObjectNode)json.readTree(x[0]),(ObjectNode)json.readTree(x[1]));}catch(Exception e){throw new IllegalStateException(e);}});}catch(IllegalArgumentException e){return Mono.empty();}}
}
